### ISSUE TITLE
Using with module-based store

### ISSUE THREAD

**Issue by aalyokhin** [smirzo/vuex-observable-plugin#23]
Hi @smirzo,

Thanks for a great plugin! I'm struggling to make it work with module-based store, which I think is pretty common thing and is widely used as an approach for Vuex store architecture.
In the examples you are using strings in `ofType` calls. When using store modules I would love to have something like: 
```js
ofType(actions.START_STREAMING_NUMBERS.type)
```
instead of providing a string manually, for example (taken `general` is a store module name):
```js
ofType('general/START_STREAMING_NUMBERS')
```
As far as I know those types are there out of the box when using Redux, but it's not the case for Vuex. Could you please advise, if it's even doable or there is no other way except mentioned above? 

To make it at least not that ugly I'm using the following workaround (meh):

_modules/general/index.js_
```js
export const moduleName = 'general';
```

_modules/general/actions.js_
```js
import { moduleName } from './index';

const epicActionName = name => `${moduleName}/${name}`;

export const epicActionTypes = {
    START_STREAMING_NUMBERS: epicActionName('START_STREAMING_NUMBERS'),
    STOP_STREAMING_NUMBERS: epicActionName('STOP_STREAMING_NUMBERS'),
};
```

_modules/general/epics.js_
```js
import { epicActionTypes } from './actions';
...
ofType(epicActionTypes.START_STREAMING_NUMBERS),
...
```

Many thanks in advance.

**Comment by smirzo** [comment]
Hi @aalyokhin,

Thanks for the kind words! 

Just to make sure I understand you correctly, would this problem of having to interpolate strings also pertain to using the standard Vuex without the plugin or is the issue unique to this plugin (is using modules somehow breaking the plugin implementation)?

Cheers!
